### ISSUE TITLE
Navigation links change URL but not the page

### ISSUE THREAD

**Issue by jeremiak** [code4sac/sacramento-campaign-finance#20]
The navigation links between "City Council" and "Board of Supervisors" aren't working when clicked.

Steps to reproduce:
1. Go to the [city council page](https://sacramento-campaign-cash.netlify.app/body/sac-city)
2. Click on "Board of Supervisors" in the navigation
3. See the URL change to `https://sacramento-campaign-cash.netlify.app/body/sac-county` but the page content doesn't change
4. Refresh to see the Board of Supervisor data

**Comment by hritvikgupta** [comment]
Hey, Could you please assign me this issue. I guess i can fix it.

**Comment by jeremiak** [comment]
Hey @hritvikgupta - sorry, just saw your message after we merged #21 from @SKYang014.

What kinds of things do you like to work on/what part of the stack? I'll try and tag you next time we open some issues we want help with.
