### ISSUE TITLE
Add Tabler to the project and update home page

### ISSUE THREAD

**Issue by jeremiak** [code4sac/sacramento-campaign-finance#24]
[Tabler](https://tabler.io) is a UI framework that has a bunch of layouts, components, and even some chart integrations that seem like they'd be helpful as we build. There's even a [Svelte library with a bunch of icons](https://tabler.io/docs/icons/svelte).

We want the homepage to look like [this Figma wireframe](https://www.figma.com/file/6nz760YsTScYjxdprIySyV/Sacramento-Campaign-Cash?type=design&node-id=713-67&mode=design). I think that you should able to include the framework by adding the following to `src/app.html`:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler.min.css">
<script src="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/js/tabler.min.js"></script>
```

**Comment by natebass** [comment]
I am going to keep this issue open until we fully implement Tabler.

TablerUI has container classes that will help with margins and responsive design. We can start by using these classes in the navbar and page layout https://tabler.io/docs/layout/page-layouts
