### ISSUE TITLE
Optimizing homepage for mobile

### ISSUE THREAD

**Issue by SKYang014** [code4sac/sacramento-campaign-finance#31]
Looking to have the homepage optimized for mobile using the [figma file here.](https://www.figma.com/file/6nz760YsTScYjxdprIySyV/Sacramento-Campaign-Cash?type=design&node-id=713-67&mode=design&t=WHaDq760HNu1Ywem-0)
Project is using grid for the overlays in desktop, icons from tabler, and media screen is located in the +layout.svelte file in the routes folder.

**Comment by natebass** [comment]
We can try to add more Tabler-specific classes to make the application more responsive. Tracked in this issue too https://github.com/code4sac/sacramento-campaign-finance/issues/24
